### PR TITLE
fix: scenes fetching and tabs styles

### PR DESCRIPTION
**Pull request by rostyslavvnahornyi**

### CODE REVIEW

**Comment by kfarr** [comment]
@rostyslavvnahornyi 

here is some feedback:
* you say "fix: scenes fetching" -- what issue # does that relate to?
* the tab style for open modal is improved but still not the same as what is currently on production. Note the lighter gray of the currently selected tab. 

production - desired:
image

this PR - needs fixing:
image

* The tab highlighting on the help modal still does not work as expected

production - desired:
image

this PR - needs fixing:
image

**Comment by rostyslavnahornyi** [comment]
@kfarr this task was done to #371 and #375 issues and also style changes for tab i did linking to figma. The selected tab in figma is darker that we currently have in prod. I think maybe to ask designer to revise these styles?

**Comment by kfarr** [comment]
@rostyslavnahornyi thanks for clarifying the relevant tickets to test this against.

Please use the current style from production for "active enabled tab on tabs container" and ignore the style guide in this case.

**Comment by kfarr** [comment]
thanks @rostyslavnahornyi ! 

I validated the following:
- "save as" scenes appear correctly when re-opening open modal
- changing title and scene thumbnails appear correctly when reopening open modal
- tab styling is correct

**Pull request merged**
