### PR TITLE
add save to 3dstreet json

### PR DESCRIPTION
**Pull request by kfarr**
assumes json-utils.js functions are already accessible in global context imported from index.html script tags

still to do:
- [x] change index.html to be same basic scene as `3dstreet` core viewer -- also to include streetmix loader from # in url -- not working at present and will need to replace streetmix3d.net forwarding
- [x] save this intersection scene in a different file, then convert later to .3dstreet.json so it can be loaded as an example
- [x] test saving / loading -- loading doesn't work right now from the saved example file

### CODE REVIEW

**Comment by omedvediev** [comment]
Hello, @kfarr, I'll check what is wrong with loading of the saved exmaple.

**Comment by kfarr** [comment]
I did a basic test last night and it seems to work. Next steps:

- [x] resolve conflict with main branch - I will try this
- [x] update json_utils in `3dstreet` repo (here in `3dstreet-editor` repo it is supposed to be just a copy) based on your new changes
- [ ] once released, ask users to test this out and break it to find edge cases

**Comment by kfarr** [comment]
Checklist to merge:
- [x] backup original index.html as index-mapbox-intersection.html
- not doing - [ ] fetch json utils from `3dstreet` repo - later
- [x] test again
- not doing - [ ] add user warning or versioning - fast follow? - later

**Comment by kfarr** [comment]
things to do later:
- add user warning about brittleness of saving?
- ensure scene graph is re-loaded correctly upon load
- ensure parity of  json utils with `3dstreet` viewer repo
- add to docs
- once released, ask users to test this out and break it to find edge cases

**Pull request merged**
