### PR TITLE
feat: new save button in toolbar actions

### LINKED ISSUE #210: New dropdown save menu
(This ticket should have its own PR to be merged into master prior to the rest of save / load work)

Currently when a user clicks the save menu it pushes horizontally 2 more options and an "x" button to return. This limits the number of options to ~2 given user screen widths.

Instead, we would like to use a dropdown menu style to offer more than 2 save options. As a first step, we would like to replicate the current save menu behavior but with the new dropdown menu style. A later ticket will add more cloud save options.

image
https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=5070-122763&mode=design&t=7ufkGgfZj4PYVSDP-4

### PR DESCRIPTION
**Pull request by rostyslavvnahornyi**

### CODE REVIEW

**Comment by kfarr** [comment]
@rostyslavvnahornyi thanks for this. A few requests:
* Can you do the same treatment for the Open menu?
* Can you merge master branch into this and resolve conflicts? I started to try to do this myself but to be honest I am not so great with CSS and it's hard to tell what I should keep or not
* I have also shared with designer for any more feedback

**Comment by rostyslavvnahornyi** [comment]
@kfarr, hello)! 
Can you explain in more details the first question?
And also i have already merged the master into this branch.

**Comment by kfarr** [comment]
Great, thanks for merging in master Rosty. 

I meant that just like you did the new dropdown menu for Save, now do the exact same thing for the "Load" menu options to be a dropdown, and also rename the button label to "Open" instead of "Load"

Here is a figma for the open dropdown: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=5189-38571&mode=design&t=3jw5CrCWD7T8Qieh-4 (for now ignore cloud "Open", that is a separate task)

**Comment by kfarr** [comment]
Also here is design feedback:
1. the white button should have states such as hover, click, etc; see: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=698%3A11006&mode=design&t=ZmFOiDtLEJI8fXqU-1
2. please don't forget to add shadow when the menu is active
3. ideally there is behavior similar to an native OS dropdown menu such that if a user clicks outside of the menu the menu will close

**Review by kfarr — APPROVED** [review]
thanks, there is some odd locations for the css like putting it in scenegraph.styl instead of button component scss but I'm sure it is annoying to fix this so let's say it's ok for now

**Pull request merged**
