### PR TITLE
fix camera tiles

### PR DESCRIPTION
**Pull request by Algorush**

### CODE REVIEW

**Comment by kfarr** [comment]
@Algorush 
issues remaining:

- ~~cannot save~~ it is ok to not be able to save at the moment
- 3d tiles do not update with inspector camera (in editor mode)
- note: after this is all confirmed working, then to remove hard-coded 3dtiles entity in index.html
- ideally fix this issue as reference layer should be above viewer (camera) layer: https://github.com/nytimes/aframe-loader-3dtiles-component/issues/45

**Comment by Algorush** [comment]
> * 3d tiles do not update with inspector camera (in editor mode)

camera in Editor mode should work after applying also this PR from the Editor repo: 
https://github.com/3DStreet/3dstreet-editor/pull/410

**Comment by kfarr** [comment]
@Algorush yes I am testing on this PR #410. Here is a video of the current behavior. The component appears to not be paused (good!) but the tiles do not update based on the change of editor camera pose:

https://github.com/3DStreet/3dstreet-editor/assets/470477/129d13bd-5f2c-45b6-87c5-125f34b63bdd

**Comment by kfarr** [comment]
Also let's ignore the saving issue, it's a blessing in disguise that saving does not work

**Comment by Algorush** [comment]
Sorry, I linked in this PR instead of PR in aframe-loader-3dtiles: https://github.com/3DStreet/aframe-loader-3dtiles-component/pull/3
Camera should work with new dist of aframe 3dtiles component from this PR, have you tried with it?

**Comment by kfarr** [comment]
Ok this all works as expected now, thanks. I did have to copy this to the local repo for now. Later we could just publish this to npm and include as a dependency? I will remove from index.html and test adding via console and maybe even database

**Comment by Algorush** [comment]
I haven't added orthographic camera support yet. Almost finished it, I wanted to ask you to review it.
And also later I will add a limitation of the tiles loading area.
I will do it in 3dstreet/aframe-loader-3dtiles-component

> Later we could just publish this to npm and include as a dependency?

I don't know if we need to add camera support in the nytimes/aframe-loader-3dtiles-component yet, because it depends on this PR 410. But updating camera tiles won't work in the aframe-inspector. Later I intend to make this work for aframe-inpector as well

**Pull request merged**
