### PR TITLE
styles: open dropdown menu

### PR DESCRIPTION
**Pull request by rostyslavvnahornyi**

### CODE REVIEW

**Comment by kfarr** [comment]
@rostyslavvnahornyi great start, one last issue is that as a user, when the context menu is open and when I press the 3 dots again I expect the context menu to disappear, not re-open.

Video:
https://github.com/3DStreet/3dstreet-editor/assets/470477/226514ba-8bec-4e33-83f0-96a45c4e0562

**Comment by kfarr** [comment]
So close, but @rostyslavvnahornyi now when you click on the menu items, they do nothing (ie clicking edit does nothing, clicking delete does nothing). When the context menu is open and when I press one of the 2 menu options I expect the associated function to fire as it did prior to the most recent commit.

**Comment by rostyslavvnahornyi** [comment]
Hi @kfarr, can you pls check the last commit

**Comment by kfarr** [comment]
excellent, thank you @rostyslavvnahornyi

**Pull request merged**
