### PR TITLE
Issue#54 zoom buttons

### PR DESCRIPTION
**Pull request by omedvediev**

### CODE REVIEW

**Comment by kfarr** [comment]
Hi @omedvediev here is feedback on this zoom PR
https://github.com/3DStreet/3dstreet-editor/issues/54#issuecomment-1331649101

**Comment by omedvediev** [comment]
Hello, @kfarr, thanks, I'll check it out.

**Comment by kfarr** [comment]
this works great! I also like the ability to press and hold the zoom + / - icons

I suggest we wait until after we merge https://github.com/3DStreet/3dstreet-editor/pull/89 , then rebase and merge this

For a later, related tickets I can writeup:
- add scale indicator
- when zooming in / out, with larger distances (zoom values) increase zoom delta. As a user it "feels slower" when you zoom out for a while, even though the delta is constant the field of view doesn't increase as quickly. Perhaps zoom delta value is based on the current zoom value.

**Comment by kfarr** [comment]
@omedvediev can you help resolve conflicts on this PR so we can merge?

**Comment by omedvediev** [comment]
Hello @kfarr , I've merged 'master' into 'issue#54' and resolved conflicts. The PR is ready to be merged.

**Pull request merged**
