### PR TITLE
Added: scene url to copyboard, download as button and share modal

### PR DESCRIPTION
**Pull request by rostyslavvnahornyi**

### CODE REVIEW

**Comment by kfarr** [comment]
thanks @rostyslavvnahornyi 

here are some issues:
- can we move "Download scene as..." dropdown to the right of the copy url bar? (see image 1 below)
- the close x button does not work or show hover state unless the mouse is hovered in the upper-right 1/3rd of the x-spot. Instead, the hover and close actions should fire whenever the mouse is hovered on the x. The other modals such as open or help modals are correct, it is only this share modal that is incorrect.
- the input component displaying the URL has odd behavior and does not act the same as the input widget from the right-hand properties panel (which is correct). For example, when clicking on the scene URL text and dragging to select text, the text unselects immediately. This means a user cannot copy that text. Instead, just like normal text input widget, a user should be able to select text and it will stay selected.
- When a user hovers mouse over copy icon, the copy icon does not show hover state. Instead the text input area shows hover state. These should be separate hover areas. In fact I recommend using a separate button component for copy action, not part of the input component.

image 1:
image

**Comment by rostyslavvnahornyi** [comment]
@kfarr hi! you can see the last commit with done tasks in the branch issue#262

**Comment by kfarr** [comment]
- the "copy" icon still needs hover state (this one 
image
)
- very important -- show entirety of image from screenshot - scale instead of crop (right now the downloaded image is different from what the preview window displays)
- reducing width of display eventually results in dropdown menu not being displayed. instead, the copy and dropdown components should each take up 50/50 space
image

**Comment by rostyslavvnahornyi** [comment]
Hello! @kfarr
I have improved markup in the screenshot modal. You can see in the last commit on this branch(issue#262)

**Comment by kfarr** [comment]
this is excellent, thanks @rostyslavvnahornyi

**Pull request merged**
