### PR TITLE
feat(ga): added save scene actions and new account creation

### PR DESCRIPTION
**Pull request by rostyslavvnahornyi**

### CODE REVIEW

**Comment by kfarr** [comment]
Reviewing the code first, it looks like there is a bit more process around sign-in now so that we can do a query to see if a user is logging in for the first time therefore creating an account

**Comment by kfarr** [comment]
updated from master

other questions:
- which google analytics key -- I assume that is tied to the environment credentials dev vs. prod

how to test?
- stub the google analytics calls with console.log (or add that)
- try logging in with a new google account (or delete that account on the dev server)
- is there a way to view events being sent live on google analytics for debugging? use save / save as to test that


https://firebase.google.com/docs/analytics/debugview#web

**Comment by kfarr** [comment]
I started testing using the extension suggested above. It confirmed that we were sending events, but not to the development account as expected from the current environment file.

Then I identified that we're still loading GA via index.html 
https://github.com/3DStreet/3dstreet-editor/blob/master/index.html#L130

Instead we should instantiate google analytics via react / javascript so that we can use env credential.
https://github.com/3DStreet/3dstreet-editor/issues/390

Please make these changes on this very PR so we can keep all the google analytics changes together

**Comment by rostyslavvnahornyi** [comment]
hi @kfarr !

ive added ga via npm package react-ga4 and created new variable in envs "GA_ID". For development im using my GA_ID that i have created before. For production we need to use old GA_ID that stored in index.js at the end of the file.

Also i changed all sending events from native js to sendMetrick() function. Here i ran into a problem that all my click events were not sent to ga servers in local development due to adblockers.  So, If you want to test ga in local just remove all adblockers.

This is the example of metric(export gltf):
image
image

**Comment by kfarr** [comment]
looks great @rostyslavvnahornyi thanks for this and sorry for delayed review

**Pull request merged**
