### PR TITLE
Issue#114 Add load button

### LINKED ISSUE #114: add load button in editor
Similar to the existing `Save` button on the editor menu, add a `Load` button. When clicked, this button will show 2 more choices `3DStreet JSON` and `Import Streetmix` and an `x`.

When clicked, these are functionally equivalent to the 3dstreet index.html provided right-hand load button.

The 2 Load options of "Import Streetmix" should and "3DStreet JSON" should fire the same functions as the existing buttons placed in index.html prior to editor loading:

OLD DESIGN
image

NEW DESIGN
* Refer to Animation Prototype (make sure to click all icons including x to match behavior): https://www.figma.com/proto/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=2784%3A46984&scaling=min-zoom&page-id=2077%3A21505&starting-point-node-id=2784%3A46984
* figma source https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?node-id=2784%3A46984&t=YdoWS9BB0v4yyMfw-4

v1 of this ticket would keep the import streetmix and load 3dstreet json functions in index.html, for v2 (a future ticket) we can move the location of these functions and how they are called. (Currently they are globals imported in index.html with script tags.)

### PR DESCRIPTION
**Pull request by ihordubas1**

### CODE REVIEW

**Comment by kfarr** [comment]
* on first test the new Load > 3DStreet JSON button doesn't actually load from json (it shows the file picker menu, but it does not actually load or place the json scene.
* In other words the new button does not accomplish the same behavior as the current button on the right-hand side. Note that when loading 3dstreet json by clicking the right hand button it works. the right-hand button looks like this: 
image

attached is an example json file to test with:
[sample-3dstreet-data-7.json.zip](https://github.com/3DStreet/3dstreet-editor/files/10691549/sample-3dstreet-data-7.json.zip)

**Comment by ihordubas1** [comment]
Thanks for sharing json file to test it!
Fixed this issue, but I moved functions for loading json files in component where I added Load button.
Unfortunately, we can't import them from index.html file because they are in tag <script>.
So, it will be better to create some specific file for these functions, like we have in `lib` folder. And then import these function to Toolbar.js component and use it for Load button.

**Comment by kfarr** [comment]
> So, it will be better to create some specific file for these functions, like we have in `lib` folder. And then import these function to Toolbar.js component and use it for Load button. 
Yes this makes sense to put a file with these functions in lib folder.

In a perfect world these functions could be added to this file and it is identical in both `3dstreet` and `3dstreet-editor` repos:
https://github.com/3DStreet/3dstreet/blob/main/src/json-utils.js

however, that is common js so probably not useable as-is in this repo.

So i'm open to suggestion from you on where to put this

**Comment by ihordubas1** [comment]
> So i'm open to suggestion from you on where to put this

I think the good way will be to create in `lib` folder `toolbar.js` and put there all 4 functions which I took from `index.html`

**Comment by kfarr** [comment]
@ihordubas1 sounds good to me, yes can you do that?

**Comment by ihordubas1** [comment]
Done

**Pull request merged**
