### PR TITLE
fix: designer issues

### PR DESCRIPTION
**Pull request by rostyslavvnahornyi**
Hello @kfarr! Can you please see the changes and tell me your feedback because there were problems with the css markup. Unfortunately, in the layer and element widget, it is quite difficult to make the same hover effect animation as in other widgets. But if this does not suit you, I will try to make one to one.

### CODE REVIEW

**Comment by kfarr** [comment]
Hi @rostyslavnahornyi thanks for this. I have shared with our designer using the netlify build: https://deploy-preview-197--3dstreet-editor-builds.netlify.app/#https://streetmix.net/kfarr/3/example-street

This is on her list to review.

**Comment by kfarr** [comment]
Hi @rostyslavvnahornyi here is some feedback:
Original feedback in Figma: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=4682-109416&mode=design

I have transcribed it into key points below:

1) corner radius should be 11 for tabs.
current, wrong: 
image
instead:
image
figma style guide source for tabs: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=700-8007&mode=design&t=acbgs90WHfgPtCYo-4

2) scale button incorrect
current, wrong:
image

Instead, here are all the states for the scale button:
image

figma style guide source for zoom: https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=2784-47012&mode=design&t=acbgs90WHfgPtCYo-4

3) layers panel - corner radius 8
image

3.1) layers panel, descending characters are cut off
issue: the "g" in light (and the "y" in sky) are slightly cropped, instead the full descending characters should be visible:
image

3.2) layers panel, selected group AND entity should have slightly different hover states. 

When hovering over an entity within an expanded section, if the section is expanded then the whole section should highlight ("focus") AND the individual row should be a slightly different color ("hover") see https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=792-9506&mode=design&t=SP2NqdfhixTzkb6g-4 

4) zoom reset button, designer says "i changed icon so now when you hover it should change color evenly" 
image

5) model search dropdown combo text box: selector box should have the same height as the normal input
image

6) hovering over a hidden entity moves by approx 1 pixel; it should not change position when hovered
issue:
https://github.com/3DStreet/3dstreet-editor/assets/470477/902dcdb9-4f63-438a-af1b-fcc70ac53812

7) regression: save and load buttons no longer condense in tablet mode. As part of https://github.com/3DStreet/3dstreet-editor/issues/165 text is removed from save and load buttons, only the icons remain below 1024w screen size. This change from 165 has been lost recently.

**Comment by rostyslavvnahornyi** [comment]
@kfarr Hi! 
I changed the styles, Can you ask the designer to check new changes? I will be very grateful)

**Comment by kfarr** [comment]
Next round of feedback:

(1) First, I love the new addition of hovering over a top-level layer like `Environment` or `2D Street Layers` shows the purple outline! Looks great! But the right-hand side of the hover outline appears to be missing for me

image

(2) the collapse arrow on right-hand properties panel should be in opposite direction: (see current state in 3dstreet.app is correct behavior)
image

(3) the right-hand hover state should include icon even when entity label is blank (see current state in 3dstreet.app is correct behavior)
image

(4) the right-hand hover state label should not wrap

example from this PR, incorrect behavior with wrapping
image

example of viewer button, correct wrapping behavior:
image

(5) Note the icon for right-hand panel should be the box instead of the layers icon. 
Correct behavior:
image

(6) Left-panel selected entity state - regression

Restore the current 3dstreet.app version of a selected entity having a purple background. ("enabled active" layers widget on [style guide](https://www.figma.com/file/W9jid3A0jgssnIKBFEvG38/3DStreet-2022?type=design&node-id=794-10280&mode=design&t=ppgtiRrLfh221ZK3-4)) That has been lost in this version.
current state video - selection only, hover does not exist in current state:
https://github.com/3DStreet/3dstreet-editor/assets/470477/45093adb-6738-4d3e-ac67-59fbe07d4232

Perhaps the only changes in this repo with regards to left-hand scene graph styling should probably be hover states only, I think. But even hover states have many variants -- hover over selected entity, hover over unselected entity, hovering any entity within a top level layer (which looks great except for the missing right-hand border), etc.

**Comment by kfarr** [comment]
thanks, here is feedback:

- [x] 1 - resolved
- [ ] 2 - not resolved
- [x] 3 - resolved
- [x] 4 - improved
- [x] 5 - resolved
- [x] 6 - improved

Good enough to merge

Carryover to next ticket:
- right-hand panel properties, reverse arrow
- hover states on individual entities in left-hand panel not implemented
- "layer" hover state pushed right-side collapse arrows, should not
- object title wrapping, see suburban house example
image
- arrow from outline to solid
- regression, left-hand panel corner radius
image

**Comment by kfarr** [comment]
thanks @rostyslavvnahornyi and @ViktoriaShurhot this is 90% complete so good enough to merge. I have broken out unfinished things into a new ticket https://github.com/3DStreet/3dstreet-editor/issues/208

**Pull request merged**
