### PR TITLE
Issue#101 v0 Add selector with static data

### PR DESCRIPTION
**Pull request by ihordubas1**

### CODE REVIEW

**Comment by ihordubas1** [comment]
Hi @kfarr 
I added basic functionality with mock data for this ticket (I'll change it in the next version).
But the question is open: which data do we need to set in this Select?

**Comment by kfarr** [comment]
sorry i did not provide more context

instead this should make use of mixin component widget which is already existing in the a-frame inspector. You can test by removing line 57 in index.html and selecting an entity using the native a-frame inspector. You will see the native mixin property widget.

I just made a commit to restore this so you can see it.

A few points:
- you'll notice that the native mixin widget populates options based on mixins defined in the scene.
- by default the mixin component allows for multiple mixins per entity. this is desired behavior in some cases, for example when a street surface has both a road texture and a color modifier.
- however, for most object placements we only want one mixin at a time and currently a user has to be savvy to delete the unused mixin after selecting a new one.
- perhaps we could modify behavior such that if an entity has only 1 mixin defined, then the mixin widget will allow for selection of another mixin to replace instead of adding the mixin in addition.
- alternative brainstorm: if we change this behavior to replace mixin instead of add mixin, perhaps we can retain the existing behavior of add mixin with a keyboard modifier of `control` or `command` key when selecting

**Comment by ihordubas1** [comment]
Thanks @kfarr for providing more info 
I reverted my changes and used `Mixins` 
Is it ok to use this component for now ?

**Comment by kfarr** [comment]
@ihordubas1, yes this is an excellent v0 for user testing!

**Pull request merged**
